### ISSUE TITLE
Infografia calidad de software y pruebas

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-saul19bautista#1]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-saul19bautista/files/15476363/Infografia.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Calificacion 20
